config_name: hyper_unet, channels=2
description: "hyper config, channels=2"

n_channels: 2
n_classes: 2
ph_n: 2  # Setting the Kronecker Decomposition Dimension
epochs: 50

cuda: True

dataset_name: modl_dataset
dataset_params:
  dataset_path: 'data/demoImage.hdf5'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: base_modl

restore_weights: final #False, best, inter, final
restore_path:

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True